POST http://localhost:{PORT}{SubRoute}/{EndPoint}/{FileName}
Content-Type: application/json

[
    {
        "Name":"Keshav",
        "Mobile":9848163021
    },
    {
        "City":"Kakinada"
    }
]